### ISSUE TITLE
How to remove this plugin?

### ISSUE THREAD

**Issue by lingliugithub** [QL-Win/QuickLook.Plugin.OfficeViewer-Native#10]
Hi,
Thanks for develop this plugin.
I installed but this plugin fails in loading xls files (but it works on word and ppt files though).
How could I remove this plugin? I found nothing like .Plugin.OfficeViewer in my "QuickLook-3.6.5\QuickLook.Plugin" folder.
Would you kindly let me know how to remove so that I can revert back to the default viewer? Thanks!

**Comment by xupefei** [comment]
See this: https://github.com/QL-Win/QuickLook/wiki/Available-Plugins#how-to-remove-a-plugin
